brew "coreutils"
brew "bash-completion"
brew "bash-completion@2", conflicts_with: ["bash-completion"]
brew "duti"
brew "git-number"
brew "git"
brew "gnupg"
brew "jenv"
brew "jq"
brew "node"
brew "nvm"
brew "openssl"
brew "p7zip"
brew "pinentry-mac"
brew "pyenv"
brew "rbenv"
brew "ruby"
brew "vim"
brew "whalebrew"
brew "yarn"

tap "homebrew/cask"
tap "adoptopenjdk/openjdk"
cask_args appdir: "/Applications"

cask "adoptopenjdk11"
cask "adoptopenjdk8"
cask "alfred"
cask "cheatsheet"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "keepingyouawake"
cask "maccy"
cask "postman"
cask "visual-studio-code"
